code/modules/client/client_procs.dm

fix: view set crutch

---

code/modules/mob/mob.dm

feat: add map CPU to MC tab

---

maps/using.dm
mods/~_ss220/text2speech/code/hear.dm
mods/~_ss220/text2speech/code/tts_preferences.dm
mods/~_ss220/text2speech/code/tts_subsystem.dm

ПР делает что-то умное
close #0
```yml
🆑furior
rscadd: Возможность отключить ттс
rscadd: Автовыдача случайного сида, если никакой не установлен
/🆑
```

Tweak: tts

---

.github/workflows/changelog_generation.yml
.github/workflows/check_changelog.yml
.github/workflows/codeql-analysis.yml
.github/workflows/labeler.yml
.github/workflows/make_changelogs.yml
.github/workflows/test.yml
tools/changelog/generate_cl.py

Не мержить, пока не сбилжу релиз в нашу репо растг

Tweal/fix: change base branch to master and repo links to actual

---

code/controllers/configuration.dm
code/modules/admin/admin.dm
code/modules/admin/admin_verbs.dm
code/modules/client/client_procs.dm
code/modules/mob/observer/ghost/ghost.dm
config/example/config.txt
mods/client_verbs/_client_verbs.dme
mods/client_verbs/code/sendbacktolobby.dm
mods/client_verbs/code/set_respawn_timer.dm

Admin verbs finaly get healing touch of doctor
```yml
🆑imjustkisik
admin: Добавил возможность вертать людей в лобби
admin: Добавил возможность изменять время респавна не через ВВ
/🆑
```

RSCADD: Remove lack of admin verbs

---

baystation12.dme
code/__defines/subsystem-priority.dm
code/controllers/subsystems/processing/overmap.dm
code/modules/overmap/ships/computers/helm.dm
code/modules/overmap/ships/ship.dm

Добавил процессинг для овермапы, от чего она будет в хайпоп меньше лагать. Вот. 
:cl:
experiment: Добавил процессинг овермапы, для уменьшения лагов космоперелётов
/:cl:

Remove absence of overmap processing

---

code/modules/mob/new_player/login.dm
maps/mapsystem/maps.dm

Чищу код за собой.
Не вызываем показ окошка лобби скрина дважды
Меньше говна в коде
Почистил кеш, клин компалнул - всё показывает

fix: invoke title screen show async

---

code/_helpers/text.dm

Фикс кириллицы в именах
КИРИЛЛЛЛ
- Перс с кириллицей в имени
- Почта с кириллицей
- Написал почту себе - почта пришла
- Крю манифест - работает
- Имя - работает
:cl:
fix: Имена на кириллице
/:cl:

Fix Cyrillic names

---

code/modules/mob/hear_say.dm

рунчат для языка знаков
Поговорил ГБС на своём, рунчат появился. Человек не понял и получил рунчат без сообщения
:cl:
add: Рунчат для языка знаков
/:cl:

runechat for sign language

---

baystation12.dme
code/_helpers/cyrillic_keys.dm
code/_helpers/text.dm

Не знаю
Кириллица удаляется с почты, если ставить вручную
:cl:
tweak: Почту теперь создать на кириллице
/:cl:

transliterate emails

---

code/controllers/subsystems/jobs.dm

Фиксит проверку на возраст на latejoin
Ура ура лидер флота на патруле
За ГБС зашел на станцию
За хумана зашел за лидера патруля
:cl:
fix: Фикс проверки на возраст при latejoin
/:cl:

fixes check for age for latejoin

---

maps/sierra/sierra_lobby.dm

Невероятный, прекрасный и просто лучший трек от Duke Gneiss под названием Exploring
Еще больше прекрасной музыки в лобби
Find out ingame
:cl:
soundadd: Невероятный саундтрек от Duke Gneiss - exploring
/:cl:

feat: adds beautiful music by Duke Gneiss: `Exploring`

---

.github/labeler.yml

Labeler Fix

---

.github/labeler.yml

Теперь точно должен работать, на паре это проще сделано...

Fix Labeler 2

---

mods/~_ss220/text2speech/code/tts_subsystem.dm

ГБС -> Гэ Бэ Эс
ЦПСС -> Цэ Пэ Эс Эс
ГКК -> Гэ Кэ Ка

TTS acronyms fix

---

code/game/gamemodes/endgame/bluespace_jump/bluespace_jump.dm

:cl:
fix: Починил оверлей блюспейса при прыжке 
/:cl:

Remove lack of blue bluspace

---

code/datums/mind/mind.dm
code/game/antagonist/antagonist.dm
code/game/antagonist/antagonist_add.dm
code/game/antagonist/antagonist_create.dm
code/game/antagonist/antagonist_factions.dm
code/game/antagonist/antagonist_helpers.dm
code/game/antagonist/outsider/actors.dm
code/game/antagonist/outsider/vox.dm
code/game/antagonist/station/changeling.dm
code/game/antagonist/station/cultist.dm
code/game/antagonist/station/rogue_ai.dm
code/game/antagonist/station/thrall.dm
code/game/gamemodes/cult/runes.dm
code/modules/mob/living/simple_animal/borer/borer_attacks.dm
code/modules/spells/artifacts/spellbound_servants.dm
code/modules/spells/contracts.dm

Добавляет ограничение расы на антажничество. Конвертация позволяет обходить это ограничение.
Раундстартом и авто-трейтор не будут выдавать трейторки тем, кто ИЦ не может быть антагонистом
- Раундстартом не дало трейтора (возможно и не срабатывает, но должно сработать)
- Через плеер панель можно выдать трейтора
:cl:
add: Добавлено ограничение ГБС на антаг-роли, кроме как Генокрад
/:cl:

Species restriction antags

---

code/game/gamemodes/endgame/bluespace_jump/bluespace_jump.dm

Reverts ss220club/WyccerraBay220#55

Revert "Remove lack of blue bluspace"

---

code/__defines/_renderer.dm
code/controllers/subsystems/skybox.dm

Чиним скайбокс и фиксим баг с космическую пылью из-за которого пыль не отображалсь
Красивый скайбокc
<details>
</details>
Скомпилил, протестил. Детали на фото
:cl:
fix: Скайбокс снова работает, и космическая пыль так же
/:cl:

fix: return of the skybox, and also space dust

---

maps/sierra/sierra.dm

disable broken `miningpirate` away site
Сломанная авейка повышает инициализацию до 600 секунд
Компилится
:cl:
tweak: Временно отключена сломанная авейка `miningpirate`
/:cl:

tweak: disable broken `miningpirate` away site

---

code/controllers/subsystems/presence.dm

make SSpresence not runtime
Bugs bad
Compiles, works

fix: make SSpresence not runtime

---

code/game/objects/items/weapons/cards_ids.dm
interface/skin.dmf

Снижаем время генерации картинки на id карту до минимума. 
Должно исправить проблему с очень долгим стартом раунда из-за генерации картинок с помощью 
`getFlatIcon`
Остутствие пролагов хорошо
<details>
</details>
Компилится, не рантаймит. Детали на фото
:cl:
add: Использование игровой модельки персонажа для отображения на id карте
/:cl:

Id card image map

---

code/controllers/subsystems/garbage.dm
code/modules/research/research.dm

Снова правильно сортируем технологии в фабрикаторах
:cl:
fix: Правильная сортировка технология в фабрикаторах
/:cl:

fix: properly sort designs again

---

code/modules/ventcrawl/ventcrawl_atmospherics.dm

Передвижение по диагонали в вентах теперь не выплевывает ползуна
Ползал по вентам по кардиналам, ползал по вентам диагонально
:cl:
fix: Передвижение по диагонали в вентах теперь не выплевывает ползуна
/:cl:

fix diagonal ventcrawl

---

code/game/machinery/kitchen/smartfridge.dm

Убрал размер окна с DM, забыл после нано удалить
Рантаймы плохо

SmartFridge runtime fix

---

code/modules/mob/inventory.dm
code/modules/mob/living/carbon/human/inventory.dm

Взял код отсюда: https://github.com/vlggms/tegustation-bay12/pull/157 
Нормальный квик эквип, который складывает сначала в слоты персонажа, потом в рюкзак.

Better quick-equip on E

---

code/modules/tgui/external.dm
code/modules/tgui/tgui_panel/tgui_panel_external.dm

Refresh TGUI больше не должен создавать белые окна.
Fix chat теперь в Special Verbs
Fix TGUI удалён

Refresh TGUI fix

---

code/_helpers/global_lists.dm
code/modules/client/preference_setup/general/02_body.dm

Удалил хуманов из выбора рас, а то у нас больно много рас
Много рас - плохо
<details>
</details>
Да

Delete HUMAN species

---

code/modules/mob/living/carbon/alien/life.dm
code/modules/mob/living/carbon/carbon.dm
code/modules/mob/living/carbon/human/life.dm
code/modules/mob/living/life.dm
code/modules/mob/mob.dm
code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Drinks.dm

Фикс автоматического поднятия после статус эффектов Paralyse, Weaken и Sleeping
:cl:
fix: Фикс автоматического поднятия после статус эффектов Paralyse, Weaken и Sleeping
/:cl:

fix lying status not updating

---

code/game/machinery/doors/airlock.dm
code/game/machinery/doors/door.dm

Оптимизация дверок, убрал их из процессинга и перевёл их на таймеры. 
Экономия четырех миллионов вызовов процессинга на двери. 
Двери закрываются.
NPFC

refactor: Door closing optimization

---

code/__defines/turfs.dm
code/_helpers/atom_movables.dm
code/_helpers/turfs.dm
code/controllers/subsystems/ambient_lighting.dm
code/datums/proximity_trigger/turf_selection.dm
code/game/gamemodes/cult/narsie.dm
code/game/machinery/bluespace_drive.dm
code/game/objects/effects/spiders.dm
code/game/objects/structures.dm
code/game/turfs/turf.dm
code/game/turfs/turf_ao.dm
code/modules/clothing/suits/armor.dm
code/modules/mechs/mech_movement.dm
code/modules/mob/living/simple_animal/friendly/mushroom.dm
code/modules/mob/living/simple_animal/hostile/antlion.dm
code/modules/mob/mob_movement.dm
code/modules/projectiles/gun.dm
code/modules/reagents/Chemistry-Recipes.dm
code/modules/shieldgen/emergency_shield.dm
code/modules/shuttles/landmarks.dm

Чинит поиск турфов для бумбокса, а может еще что-то.
:cl:
fix: Бумбоксы работают
/:cl:

fix square turf selection if origin is inside another atom

---

code/modules/recycling/disposal.dm

Я очень умный
Карго не взрывается

Fix disposal flushing

---

code/modules/crafting/_crafting_holder.dm
code/modules/crafting/_crafting_stage.dm

Фиксит крафтинг, проверено на ед209
:cl:
fix: Исправлен крафт, в частности ед209
/:cl:

fix crafting

---

code/modules/multiz/structures.dm

ПКМ по лестнице спускается, ЛКМ по лестнице поднимается
:cl:
tweak: Теперь ПКМ по лестнице спускается, ЛКМ по лестнице поднимается
/:cl:

ladder up on LMB, ladder down on RMB

---

code/game/machinery/doors/airlock.dm
code/game/objects/items/weapons/tools/weldingtool.dm
code/game/objects/structures/catwalk.dm
code/game/objects/structures/crates_lockers/closets/__closet.dm
code/game/objects/structures/girders.dm
code/game/objects/structures/grille.dm
code/game/objects/structures/lattice.dm
code/game/objects/structures/wall_frame.dm
code/game/objects/structures/window.dm
code/game/turfs/simulated/floor_attackby.dm
code/game/turfs/simulated/wall_attacks.dm
code/modules/mechs/mech_wreckage.dm
code/modules/projectiles/guns/energy/special.dm
code/modules/surgery/robotics.dm

Плазмакаттер теперь может быть использован как сварочный аппарат.
Меньше сноуфлейк кода
Распилил болты у двери, сварил дверь, сварил гирдер
:cl:
add: Плазмакаттер теперь может быть использован как сварочный аппарат.
/:cl:

plasmacutter is welder

---

code/modules/overmap/ships/computers/helm.dm

:cl:
tweak: Вождение кораблей пьяным делает смешно
/:cl:

Remove lack of drunk driving

---

code/modules/mob/living/carbon/human/examine.dm

Возвращает дескрипторы (меньше/больше вас и тд)
:cl:
fix: Дескрипторы сравнения при Examine вернулись
/:cl:

Return Examine Descriptors
