ss220club/WyccerraBay220

code/modules/ZAS/Turf.dm
code/modules/ZAS/Zone.dm
code/modules/xgm/xgm_gas_data.dm
code/modules/xgm/xgm_gas_mixture.dm

Проблема состояло в том, что вокруг сьеры. на 50000 турфов, шло обновление температурного оверлея, когда газа было около 0.001 моля на турф. 
Так же небольшой рефактор названий переменных.
Убирает ужасные лагспайки при вызове `update_graphic` 50000 раз каждые 2 секунды
Нет.
Скомпилировал, проверил корректность обновления оверлеев, там где обновление должно происходить
:cl:
fix: Не обновляем на турфах температурный эффект, когда это не нужно
/:cl:

refactor: don't make temp overlay update if no gas overlay is displayed

---

code/game/objects/items/weapons/material/misc.dm

Closes https://github.com/ss220club/WyccerraBay220/issues/43
Замена очень хуевого звука у топорика (в т.ч. мачете)
Понятный звук удара
<details>
</details>
<details>
<summary>Видео</summary>
</details>
:cl:
tweak: Заменил звук у топорика
/:cl:

Replace hitsound for hatchet

---

code/game/gamemodes/changeling/changeling_powers.dm
code/game/gamemodes/changeling/modularchangling.dm
code/modules/nano/interaction/default.dm
code/modules/nano/nanoui.dm

Фиксит баги с меню эволюции генокрада и вайдскрином.
Добавляем стактрейс когда наноуи имеет юзера типа отличного от `/mob`
Баги это плохо, отсутствие багов хорошо
Скомпилил, поотрывал менюшки, потыкал кнопки - рантаймов нет
:cl:
fix: Исправляет баги связанные с меню эволюции генокрада 
fix: Исправляет очередную пачку ошибок связанных с вайдскрином
/:cl:

fix: fix runtimes related to changeling and widescreen, `stack_trace` when nanoui user is of invalid type

---

interface/skin.dmf

У рунчата правильные стили и шрифт (MS Serif), поддерживающий специфические для кириллицы буквы шрифт
UI/UX
<details>
</details>
Компилится, результат на скрине.
:cl:
fix: Runechat снова имеет правильные стили
/:cl:

fix: fix runechat style

---

code/modules/recycling/conveyor2.dm

Убираем `in world` где он не нужен
Меньше лагспайков - лучше
Компилируется, не рантаймит
:cl:
fix: Не перебираем все рычаги в мире при нажатии на один. Меньше лагов
/:cl:

fix: don't iterate world

---

code/datums/movement/mob.dm

Убирает ретурн в муве, когда моб уже по факту начал движение и не должен ретурниться.
Можно грабать себя и ломать себе конечности без проблем для ног.
Грабнул себя, вывехнул себе руку, я могу ходить.
:cl:
fix: Граб по себе больше не ломает движение. Можно выворачивать себе руки и все еще иметь ноги!
/:cl:

Fixes grab-self

---

code/modules/tgui/tgui_input/text_input.dm

Позволяет использовать кириллицу корректно в текст инпуте (проверка на длину текста)
Создал куклу с именем "Проверка Проверка Проверка" (которая не создавалась без фикса)
Зашел в раунд - имя сохранилось
:cl:
fix: Теперь можно ставить имена в длину 26 на кириллице
/:cl:

Fixes length to length_char in tgui text input

---

code/modules/mechs/mech_interaction.dm

Теперь для активации модуля (attack_self) можно просто по нему тыкнуть, а не сначала выбрать, а потом тыкнуть.
Выглядит упорото, но иначе нужно будет полностью рефакторить логику тыков по хардпоинтам/модулям/пространству. Задача на будущее.
Делает использование более юзер френдли
Зашел в меха, выбрал карабин, тыкнул в фонарик и флеш, фонарик и флеш работают без выбора.
:cl:
tweak: Мехи могут использовать модули без необходимости выбора (особенно полезно для тех, которые выбирать нет смысла)
/:cl:

Mechs can activate modules without selecting it

---

code/game/machinery/embedded_controller/airlock_program.dm

Изменяет tolerance аирлока до 0,5 - самое низкое число, которое не приводило к замедлению его цикла. Это должно уменьшить количество утечек воздуха из шлюзов, работающих по циклу с внешней средой.
Изменено целевое внешнее давление для внешних шлюзов с 1000 на MAX_PUMP_PRESSURE, для ускорения циклинга на вулканических планетах с очень высоким давлением. К сожалению, некоторые планеты все еще могут генерировать давление, превышающее это значение.
:cl:
tweak: Ускорил работу шлюзов
/:cl:

Remove lack of airlock speed

---

code/game/antagonist/antagonist.dm

Убирает у дион и адхерантов возможность стат раундстарт/авто-антагом. Только конвертация.
Дионы и Адхеранты и так не могут стать генокрадами, так как их нельзя сканировать, обновлять тот лист не стоит
Лор?
:cl:
add: Дионы и Адхернаты не могут стать раундстарт/авто-антагом.
/:cl:

remove diona/adherant antags

---

code/modules/client/preference_setup/general/05_preview.dm

Возвращает preview toggles
Багов не должно быть
<details>
</details>
Скомпилил, на скрине видно кнопки.
:cl:
fix: Вернул preview toggles
/:cl:

fix: return back preview toggles

---

code/datums/category.dm
code/datums/underwear/underwear.dm
code/modules/client/preference_setup/general/03_equipment.dm

Возвращение блудных трусов. Теперь можно выбирать трусы опять
Не все любят стандартные трусы
Компилится, трусы меняются, персонаж сохраняется. Рантаймов нет
:cl:
fix: Трусы снова меняются на персонаже в настройках персонажа
/:cl:

fix: you can change underware again

---

code/_helpers/game.dm
code/_onclick/hud/hud.dm
code/_onclick/hud/movable_screen_objects.dm
code/game/objects/items.dm
code/modules/admin/verbs/randomverbs.dm
code/modules/client/preference_setup/loadout/lists/documents.dm
code/modules/mob/login.dm
code/modules/nano/interaction/default.dm
code/modules/overmap/ships/computers/ship.dm
code/modules/tgui/states.dm
code/modules/tgui/states/default.dm

Исправляем проблемы с вайдскрином. Теперь он корректно обновляется после бинокля, консоли и тд
Не будет необходимости каждый раз тыкать настройку, дабы получить вайдскрин обратно
Компилится, рантаймов нет, вайдскрин работает как надо
:cl:
fix: Исправил проблемы с вайдскрином
/:cl:

fix: most of widescreen issues fixes. Make documents loadout free

---

baystation12.dme
code/__defines/dcs/signals/signals_object.dm
code/modules/projectiles/gun.dm
code/modules/projectiles/guns/launcher/grenade_launcher.dm
code/modules/projectiles/guns/projectile/automatic.dm

Добавляет сигнал для `proc/toggle_safety`
Использует сигнал для переключения сейфити у underslung launcher
Фиксит переключение сейфити
Пострелял с буллпапа, выстрелил гранатой
Пострелял с лазгана, выстрелил гранатой
:cl:
fix: Теперь bonfire лазган может стрелять из подствольного гранатомета
/:cl:

add toggle safety signal, use it for underslung launcher

---

code/controllers/configuration.dm
code/controllers/subsystems/ticker.dm
code/modules/admin/topic.dm
config/example/config.txt

Добавляем возможность отключить голосование за гейммод. Ставим сикрет по-умолчанию
1984
Компилится, работает. Режим выбирается корректно

tweak: add ability to disable roundstart vote, make `secret` master gamemode

---

code/game/gamemodes/cult/cult_items.dm
code/game/gamemodes/cult/runes.dm

Теперь одежда культиста выдается всегда. Даже если у тебя нет ничего. 
Ранее  после использования руны поднимались вопросы "почему ничего не произошло".
:cl:
tweak: cult armor rune logic tweak
/:cl:

cult armor always issued

---

baystation12.dme
code/_helpers/lists.dm
code/controllers/subsystems/initialization/misc_late.dm
code/controllers/subsystems/initialization/xenoarch.dm
code/controllers/subsystems/machines.dm
code/controllers/subsystems/mapping.dm
code/modules/mining/mine_turfs.dm
code/modules/xenoarcheaology/sampling.dm
code/modules/xenoarcheaology/tools/tools.dm
maps/mapsystem/maps.dm

Ксеноархеология теперь инициализируется за 0 секунд.
Не проходим по всему миру, чтобы отыскать турфы с рудой, а по кешу
Быстрее инициализация
Без рантаймов, турфы для артефактов выбирает корректно
:cl:
fix: Скорость инициализации археологии снижена до почти минимума
/:cl:

refactor: make xenoarch initialize for not an eternity

---

code/controllers/subsystems/garbage.dm
code/modules/tgui/tgui_input/list_input.dm

Не вызывает qdel на списке примитивов. 
Компилится, рантаймов нет в тех местах где были.

fix: don't qdel primitive types

---

code/datums/communication/looc.dm

Дает видеть лоок всем мобам в рендже world.view
<details>
</details>
<details>
<summary>Видео</summary>
</details>
:cl:
fix: Теперь лоок видно в отключке
/:cl:

Fix: looc cant be viewed by blind mobs

---

code/modules/mining/machinery/mineral_console.dm
maps/sierra/job/jobs_cargo.dm
mods/_maps/farfleet/maps/farfleet-1.dmm
mods/_maps/farfleet/maps/farfleet-2.dmm
test/check-paths.sh

Работа с отзывами пользователей о недочётах карты Пионерского Корпуса. Добавлен ряд вещей
* Бумага на мостик и в брифинг + проектор в брифинг
* Банки с икрой и консервы в холодильник
* Шашки в столовую
Исправление проблем с отсутствием QoL вещей для ГКК
Локально запускал карту. Уверяю, мне можно доверить мапфиксы
:cl: LordNest
add: Различные QoL вещи для ГКК.
fix: Теперь холодильники и шахтёрские консоли не скрываются под стенками, потому что стенок нет. 
fix: Количество шахтёров уменьшено до 3, как и планировалось (откуда притащили четвертого - загадка)
/:cl:

MAPFIX: Farfleet papers and Sierra issue fixes

---

code/modules/mob/living/carbon/human/human_helpers.dm

Так как теперь каждый тик считается урон по глазам, это наносит 10-и кратный урон. Упс.
Теперь урон наносится в 10% случаев.
Глаза не ваншотаются от случайного тыка по двери сваркой
:cl:
fix: Сварочный аппарат наносит урон глазам не 10 раз в секунду, а в среднем 1 раз в секунду.
/:cl:

remove eyes oneshot

---

code/game/machinery/alarm/alarm.dm

Чинит сенсоры аир алярм, уж слишком чувствительные они были
Аир алярмы не пищат от 0.01 моля форона в больших зонах
Компилировал, заспавнил газ. Алярмы реагируют адекватно
:cl:
fix: Air Alarm не реагирует на ничтожно малые обьемы опасных газов
/:cl:

fix: properly get other gases for atoms alarm

---

code/game/jobs/whitelist.dm
code/modules/client/preference_setup/general/02_body.dm
code/modules/mob/new_player/new_player.dm

Использование стандартной проверки на вайтлист, вместо вспомогательного прока, для ППТ вайтлиста.
:cl:
fix: Теперь снова можно брать ППТ при выключенном ксено-вайтлисте
/:cl:

Use correct proc for checking FBP xeno-whitelist

---

code/game/objects/items/weapons/storage/storage.dm

Фикс обновления интерфейса контейнера, когда вытаскивают контейнер из контейнера с помощью драг-энд-дропа.
:cl:
fix: Фикс обновления интерфейса контейнера, когда вытаскивают контейнер из контейнера с помощью драг-энд-дропа.
/:cl:

fix ui when storage is removed from another storage

---

code/modules/mob/living/living.dm

Перемещает сообщения об уроне от пулла с ту-чата в баллун-алерты
Меньше смотреть в чат
:cl:
tweak: Сообщение о получении урона от пулла перемещено с ту-чата в баллун-алерты
/:cl:

damage from pulling from to_chat to balloon

---

tgui/packages/tgui-panel/styles/components/Notifications.scss

Перемещает уведомления ТГчата наверх
Можно нормально читать чат пока сервер загружается (Что очень долго)
<details>
</details>

Move TGchat notifications to the top
